[package]
name = "rist"
version = "0.1.0"
edition = "2021"

[env]
CARGO_PKG_REPOSITORY = "https://github.com/oxydien/rist"
CARGO_PKG_DESCRIPTION = "A Rust-powered, private, open-source, self-hosted file-sharing solution"
CARGO_PKG_LICENSE = "MIT"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket-governor = "0.2.0-rc.3"
rocket_cors = "0.6.0"
serde = "1.0.208"
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }

# TODO: Remove when new SQLX version is released
# JSONB support if needed
# https://github.com/launchbadge/sqlx/commit/352b02de6af70f1ff1bfbd15329120589a0f7337 
sqlx = { git = "https://github.com/launchbadge/sqlx.git", rev = "352b02de6af70f1ff1bfbd15329120589a0f7337", features = [ "runtime-tokio", "sqlite", "macros"] }
sha2 = "0.10.8"
hex = "0.4.3"
uuid = { version = "1.10.0", features = ["v4"] }
reqwest = { version = "0.12.7", features = ["stream"]}
regex = "1.10.6"
serde_repr = "0.1.19"
colored = "3.0.0"
