
const colorPrefabs = [
    16218491,
    10940572,
    16244857,
    9940477,
    16218543,
]

const chatUsernames = [
    "Zox",
    "Vix",
    "Qor",
    "Kely",
    "Nyxar",
    "Zirun",
    "Xylos",
    "Kalith",
    "Vexora",
    "Dravun",
    "Zynth",
    "Kaeloki",
    "Varisth",
    "Thrombe",
    "Qelivor",
    "Nyxantor",
    "Pyrakis",
    "Solokai",
    "Talyxion",
    "Jexoran",
    "Zovakius",
    "Rykorian",
    "Baelonix",
    "Cyventhor",
    "Fynokis",
    "Galyxiana",
    "Hryvatho",
    "Javorius",
    "Klyntarix",
    "Lyrakith",
    "Myrixian",
    "Norixora",
    "Pylosiana",
    "Qyrenoxis",
    "Rylokiun",
    "Silythoris",
    "Tyvoriana",
    "Vynoxisth",
    "Wylokoria",
    "Xyvoriana",
    "Yryxionix",
    "Zylokisth",
    "Kavaxoria",
    "Zefunixis",
    "Tykorinth",
    "Malixoria",
    "Rovexiana",
    "Kaldvornix",
    "Xylomandor",
    "Vexilaristh"
];

export { colorPrefabs, chatUsernames }
